apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: result
spec:
  containers:
    - name: result-app
      image: result-app
      ports:
        - containerPort: 80