apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote-app
        image: vote-app
        ports:
        - containerPort: 80