Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS

  # 1. Ansible Controller Node
  config.vm.define "ansible-controller" do |node|
    node.vm.hostname = "ansible-controller"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # 2. Target Server (Needs >= 2 CPUs and 4GB RAM for Minikube)
  config.vm.define "target-node" do |node|
    node.vm.hostname = "target-node"
    node.vm.network "private_network", ip: "192.168.56.20"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
      # Nested virtualization is required for Minikube inside VirtualBox
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end
  end
  
end